# Generated by Django 5.0.14 on 2025-07-10 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('is_successful', models.BooleanField(default=False, verbose_name='Успешно')),
                ('transaction_id',
                 models.CharField(blank=True, max_length=100, null=True, verbose_name='ID транзакции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order',
                                               verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
    ]
