# Generated by Django 5.0.14 on 2025-07-13 06:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_privacypolicy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name': 'Политика конфиденциальности '},
        ),
    ]
