# Generated by Django 5.0.14 on 2025-07-13 06:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_alter_privacypolicy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name': 'Политика конфиденциальности',
                     'verbose_name_plural': 'Политика конфиденциальности'},
        ),
    ]
