# Generated by Django 5.0.14 on 2025-06-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('id',), 'verbose_name': 'Корзину', 'verbose_name_plural': 'Корзины'},
        ),
    ]
