# Generated by Django 5.0.14 on 2025-06-16 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'магазин', 'verbose_name_plural': 'магазины'},
        ),
    ]
