# Generated by Django 5.0.14 on 2025-06-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_tool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='category',
            new_name='brand',
        ),
    ]
