# Generated by Django 5.0.14 on 2025-06-25 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_category_tool_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.brand', verbose_name='Брэнд'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Модель'),
        ),
    ]
