# Generated by Django 5.0.14 on 2025-07-11 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0004_alter_tool_brand_alter_tool_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('id',), 'verbose_name': 'Брэнд', 'verbose_name_plural': 'Брэнды'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ('id',), 'verbose_name': 'Инструмент', 'verbose_name_plural': 'Инструменты'},
        ),
    ]
